name: bitcoin
version: 0.17.1
summary:   peer-to-peer network based digital currency
description: |
  Bitcoin is a free open source peer-to-peer electronic cash system that
  is completely decentralized, without the need for a central server or
  trusted parties.  Users hold the crypto keys to their own money and
  transact directly with each other, with the help of a P2P network to
  check for double-spending.

grade: stable
confinement: strict
base: core18

apps:
  daemon:
    command: bitcoind
    plugs: [network, network-bind]
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  qt:
    command: desktop-launch bitcoin-qt
    plugs: [network, network-bind, desktop]
    desktop: bitcoin.desktop
  cli:
    command: bitcoin-cli

parts:
  bitcoin:
    source: https://github.com/bitcoin/bitcoin
    source-type: git
    source-tag: v0.17.1
    plugin: autotools
    override-build: | 
      git apply $SNAPCRAFT_STAGE/default_data_dir.patch
      snapcraftctl build
      make check
    build-packages:
      - g++
      - pkg-config
      - libssl-dev
      - libevent-dev
      - bsdmainutils
      # Boost.
      - libboost-system-dev
      - libboost-filesystem-dev
      - libboost-chrono-dev
      - libboost-program-options-dev
      - libboost-test-dev
      - libboost-thread-dev
      # Optional.
      - libminiupnpc-dev
      - libzmq3-dev
      # GUI.
      - libqt5gui5
      - libqt5core5a
      - libqt5dbus5
      - qttools5-dev
      - qttools5-dev-tools
      - libprotobuf-dev
      - protobuf-compiler
      # Optional.
      - libqrencode-dev
    stage-packages:
      - ca-certificates
      - libqt5test5
      - libboost-chrono1.65.1
      - libboost-filesystem1.65.1
      - libboost-system1.65.1
      - libboost-thread1.65.1
      - libboost-test1.65.1
      - libevent-2.1-6
      - libevent-pthreads-2.1-6
      - libminiupnpc10
      - libnorm1
      - libpgm-5.2-0
      - libprotobuf10
      - libqrencode3
      - libsodium23
      - libzmq5
      - libxcomposite1
      - libxcursor1
      - libxinerama1
      - libxrandr2
      - libatk1.0-0
      - libgtk2.0-0
    after:
      - berkeleydb
      - desktop-qt5
      - patches
  berkeleydb:
    source: http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz
    source-checksum: sha256/12edc0df75bf9abd7f82f821795bcee50f42cb2e5f76a6a281b85732798364ef 
    plugin: nil
    override-build: |
      cd build_unix
      ../dist/configure --enable-cxx --disable-shared --with-pic --prefix=$SNAPCRAFT_PART_INSTALL
      snapcraftctl build
      make install
    prime:
      - -*
  patches:
    source: snap/patches
    plugin: dump
    prime:
      - -*

  # Needed to supply desktop-launch
  # Paste from https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
  # Boilerplate seems to be required according to https://bugs.launchpad.net/snapcraft/+bug/1800057
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-commit: cafb789b48dc572f17fea630df18e93f507a7dff
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5